spring:
  profiles:
    active: local

grpc:
  port: 9893
  shutdown-grace: 30 # Number of seconds to wait for preexisting calls to finish before shutting down.
server:
  port: 8985
  shutdown: graceful # should support graceful shutdown, allowing active requests time to complete.